### ISSUE TITLE
Farándula

### ISSUE THREAD

**Issue by TomasEspitia** [TomasEspitia/Duitama_pages#5]

**Comment by Mejiaponte** [comment]
**Maluma, uno de los grandes invitados al concierto gratuito ‘We love NYC’**
Maluma fue incluido en el cartel de estrellas que se presentarán en el gran concierto ‘We love NYC’, en Nueva York, Estados Unidos. 
El Central Park recibirá a celebridades como Bruce Springsteen, Jimmy Fallon, Andrea Bocelli, The Killers, Carlos Santana, Jennifer Hudson, la Filarmónica de Nueva York y muchos más.
El concierto será gratuito el sábado 21 de agosto, desde las 5 de la tarde, y quienes deseen ingresar deberán portar su carné de vacunación.
